{"uuid":"eeb6377c-4fce-4a24-ac27-b445022afafe","historyId":"c5919f3b543f38d8e1e3f7f019f62e6b","fullName":"com.selenium.InsinkeratorTest.sendingEmail","labels":[{"name":"package","value":"com.selenium.InsinkeratorTest"},{"name":"testClass","value":"com.selenium.InsinkeratorTest"},{"name":"testMethod","value":"sendingEmail"},{"name":"parentSuite","value":"Default Suite"},{"name":"suite","value":"demo"},{"name":"subSuite","value":"com.selenium.InsinkeratorTest"},{"name":"host","value":"ASISH"},{"name":"thread","value":"13788@ASISH.main(1)"},{"name":"framework","value":"testng"},{"name":"language","value":"java"}],"links":[],"name":"sendingEmail","status":"broken","statusDetails":{"known":false,"muted":false,"flaky":false,"message":"Sending the email to the following server failed : smtp.gmail.com:465","trace":"org.apache.commons.mail.EmailException: Sending the email to the following server failed : smtp.gmail.com:465\r\n\tat org.apache.commons.mail.Email.sendMimeMessage(Email.java:1469)\r\n\tat org.apache.commons.mail.Email.send(Email.java:1496)\r\n\tat com.selenium.pages.SendingEmail.emailFormat(SendingEmail.java:30)\r\n\tat com.selenium.InsinkeratorTest.sendingEmail(InsinkeratorTest.java:29)\r\n\tat java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:104)\r\n\tat java.base/java.lang.reflect.Method.invoke(Method.java:578)\r\n\tat org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:139)\r\n\tat org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:664)\r\n\tat org.testng.internal.invokers.TestInvoker.invokeTestMethod(TestInvoker.java:227)\r\n\tat org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:50)\r\n\tat org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:957)\r\n\tat org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:200)\r\n\tat org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:148)\r\n\tat org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:128)\r\n\tat java.base/java.util.ArrayList.forEach(ArrayList.java:1511)\r\n\tat org.testng.TestRunner.privateRun(TestRunner.java:848)\r\n\tat org.testng.TestRunner.run(TestRunner.java:621)\r\n\tat org.testng.SuiteRunner.runTest(SuiteRunner.java:443)\r\n\tat org.testng.SuiteRunner.runSequentially(SuiteRunner.java:437)\r\n\tat org.testng.SuiteRunner.privateRun(SuiteRunner.java:397)\r\n\tat org.testng.SuiteRunner.run(SuiteRunner.java:336)\r\n\tat org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)\r\n\tat org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:95)\r\n\tat org.testng.TestNG.runSuitesSequentially(TestNG.java:1280)\r\n\tat org.testng.TestNG.runSuitesLocally(TestNG.java:1200)\r\n\tat org.testng.TestNG.runSuites(TestNG.java:1114)\r\n\tat org.testng.TestNG.run(TestNG.java:1082)\r\n\tat com.intellij.rt.testng.IDEARemoteTestNG.run(IDEARemoteTestNG.java:66)\r\n\tat com.intellij.rt.testng.RemoteTestNGStarter.main(RemoteTestNGStarter.java:105)\r\nCaused by: javax.mail.AuthenticationFailedException: 535-5.7.8 Username and Password not accepted. Learn more at\n535 5.7.8  https://support.google.com/mail/?p=BadCredentials h14-20020a170902f54e00b001c3a8b135ebsm11576982plf.282 - gsmtp\n\r\n\tat com.sun.mail.smtp.SMTPTransport$Authenticator.authenticate(SMTPTransport.java:932)\r\n\tat com.sun.mail.smtp.SMTPTransport.authenticate(SMTPTransport.java:843)\r\n\tat com.sun.mail.smtp.SMTPTransport.protocolConnect(SMTPTransport.java:748)\r\n\tat javax.mail.Service.connect(Service.java:388)\r\n\tat javax.mail.Service.connect(Service.java:246)\r\n\tat javax.mail.Service.connect(Service.java:195)\r\n\tat javax.mail.Transport.send0(Transport.java:254)\r\n\tat javax.mail.Transport.send(Transport.java:124)\r\n\tat org.apache.commons.mail.Email.sendMimeMessage(Email.java:1459)\r\n\t... 28 more\r\n"},"stage":"finished","steps":[],"attachments":[],"parameters":[],"start":1696940363637,"stop":1696940368668}